#!/bin/sh

MESSAGE_FILE=$1

grep -Eq '^TASK-[0-9]+:' "$MESSAGE_FILE"

if [ $? -ne 0 ]; then
    echo "Invalid commit message format."
    echo "Use: TASK-123: Description"
    exit 1
fi

echo "Commit message format is valid."
exit 0